export const caracDor = [
  { caracteristicasInicio: "Desconforto", doenca: "Infarto pulmonar" },
  { caracteristicasInicio: "Desconforto", doenca: "Intolerância a lactose" },
  { caracteristicasInicio: "Desconforto", doenca: "Febre tifoide" },
  { caracteristicasInicio: "Desconforto", doenca: "Prenhez ectópica" },
  { caracteristicasInicio: "Desconforto", doenca: "Gastrite" },
  { caracteristicasInicio: "Desconforto", doenca: "Porfiria aguda" },
  { caracteristicasInicio: "Desconforto", doenca: "Pielonefrite" },
  { caracteristicasInicio: "Desconforto", doenca: "Hepatite aguda" },
  { caracteristicasInicio: "Desconforto", doenca: "Hérnia diafragmática" },
  { caracteristicasInicio: "Desconforto", doenca: "Hérnia encarcerada" },
  { caracteristicasInicio: "Desconforto", doenca: "Hérnia estrangulada" },
  { caracteristicasInicio: "Desconforto", doenca: "Peritonite primária" },
  { caracteristicasInicio: "Desconforto", doenca: "Herpes Zoster" },
  { caracteristicasInicio: "Desconforto", doenca: "Pericardite" },
  { caracteristicasInicio: "Desconforto", doenca: "Ileite actínica" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Ileite de pacientes imunocomprometidos",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Ileite por AINE" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Infarto agudo do miocárdio",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Obstrução intestinal" },
  { caracteristicasInicio: "Desconforto", doenca: "Yersiniose" },
  { caracteristicasInicio: "Desconforto", doenca: "Neoplasias" },
  { caracteristicasInicio: "Desconforto", doenca: "Mucocele do apêndice" },
  { caracteristicasInicio: "Desconforto", doenca: "Infecção respiratória" },
  { caracteristicasInicio: "Desconforto", doenca: "Infecção urinária" },
  { caracteristicasInicio: "Desconforto", doenca: "Endometriose" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Doença inflamatória pélvica",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Retocolite ulcerativa" },
  { caracteristicasInicio: "Desconforto", doenca: "Úlcera gástrica" },
  { caracteristicasInicio: "Desconforto", doenca: "Doença de Crohn" },
  { caracteristicasInicio: "Desconforto", doenca: "Vasculite associada a IgA" },
  { caracteristicasInicio: "Desconforto", doenca: "Salpingite" },
  { caracteristicasInicio: "Desconforto", doenca: "Doença celíaca" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Síndrome da artéria mesentérica superior ",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Úlcera duodenal" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Síndrome de hiperemese canabinoide",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Abscesso esplênico" },
  { caracteristicasInicio: "Desconforto", doenca: "Diverticulite" },
  { caracteristicasInicio: "Desconforto", doenca: "Verminoses" },
  {
    caracteristicasInicio: "Desconforto",
    doenca: "Doença do refluxo gastro-esofágico",
  },
  { caracteristicasInicio: "Desconforto", doenca: "Tuberculose intestinal" },
  { caracteristicasInicio: "Desconforto", doenca: "Constipação" },
  {
    caracteristicasInicio: "Migratória",
    doenca: "Compressão de raízes nervosas",
  },
  {
    caracteristicasInicio: "Migratória",
    doenca: "Insuficiência suprarrenal aguda",
  },
  { caracteristicasInicio: "Migratória", doenca: "Apendicite" },
  { caracteristicasInicio: "Progressiva", doenca: "Úlcera gástrica" },
  { caracteristicasInicio: "Progressiva", doenca: "Obstrução intestinal" },
  { caracteristicasInicio: "Progressiva", doenca: "Vólvulo" },
  { caracteristicasInicio: "Progressiva", doenca: "Isquemia mesentérica" },
  { caracteristicasInicio: "Progressiva", doenca: "Neoplasias" },
  { caracteristicasInicio: "Progressiva", doenca: "Vasculite associada a IgA" },
  { caracteristicasInicio: "Progressiva", doenca: "Salpingite" },
  { caracteristicasInicio: "Progressiva", doenca: "Pancreatite" },
  { caracteristicasInicio: "Progressiva", doenca: "Úlcera péptica perfurada" },
  { caracteristicasInicio: "Progressiva", doenca: "Tuberculose intestinal" },
  { caracteristicasInicio: "Progressiva", doenca: "Peritonite primária" },
  { caracteristicasInicio: "Progressiva", doenca: "Torção de cisto de ovário" },
  { caracteristicasInicio: "Progressiva", doenca: "Tabes dorsalis" },
  { caracteristicasInicio: "Progressiva", doenca: "Pielonefrite" },
  {
    caracteristicasInicio: "Progressiva",
    doenca: "Síndrome da artéria mesentérica superior ",
  },
  { caracteristicasInicio: "Progressiva", doenca: "Ruptura de baço" },
  { caracteristicasInicio: "Progressiva", doenca: "Úlcera duodenal" },
  { caracteristicasInicio: "Progressiva", doenca: "Pericardite" },
  { caracteristicasInicio: "Progressiva", doenca: "Abscesso hepático" },
  { caracteristicasInicio: "Progressiva", doenca: "Doença de Crohn" },
  { caracteristicasInicio: "Progressiva", doenca: "Diverticulite" },
  { caracteristicasInicio: "Progressiva", doenca: "Divertículo de Meckel" },
  { caracteristicasInicio: "Progressiva", doenca: "Doença celíaca" },
  {
    caracteristicasInicio: "Progressiva",
    doenca: "Insuficiência suprarrenal aguda",
  },
  { caracteristicasInicio: "Progressiva", doenca: "Constipação" },
  { caracteristicasInicio: "Progressiva", doenca: "Febre tifoide" },
  { caracteristicasInicio: "Progressiva", doenca: "Gastrite" },
  { caracteristicasInicio: "Progressiva", doenca: "Colecistite" },
  { caracteristicasInicio: "Progressiva", doenca: "Hérnia encarcerada" },
  { caracteristicasInicio: "Progressiva", doenca: "Hérnia estrangulada" },
  { caracteristicasInicio: "Progressiva", doenca: "Crise falcêmica" },
  { caracteristicasInicio: "Progressiva", doenca: "Cetoacidose diabética" },
  {
    caracteristicasInicio: "Progressiva",
    doenca: "Ileite de pacientes imunocomprometidos",
  },
  { caracteristicasInicio: "Progressiva", doenca: "Apendicite" },
  {
    caracteristicasInicio: "Progressiva",
    doenca: "Infarto agudo do miocárdio",
  },
  { caracteristicasInicio: "Progressiva", doenca: "Infecção urinária" },
  { caracteristicasInicio: "Progressiva", doenca: "Infecção respiratória" },
  { caracteristicasInicio: "Progressiva", doenca: "Herpes Zoster" },
  { caracteristicasInicio: "Progressiva", doenca: "Infarto esplênico" },
  { caracteristicasInicio: "Referida", doenca: "Abscesso hepático" },
  {
    caracteristicasInicio: "Referida",
    doenca: "Compressão de raízes nervosas",
  },
  { caracteristicasInicio: "Referida", doenca: "Abscesso esplênico" },
  { caracteristicasInicio: "Súbita", doenca: "Crise falcêmica" },
  { caracteristicasInicio: "Súbita", doenca: "Úlcera péptica perfurada" },
  { caracteristicasInicio: "Súbita", doenca: "Cólica renal" },
  {
    caracteristicasInicio: "Súbita",
    doenca: "Adenite mesentérica (hiperplasia linfonodular)",
  },
  { caracteristicasInicio: "Súbita", doenca: "Torção de cisto de ovário" },
  { caracteristicasInicio: "Súbita", doenca: "Colite Isquêmica" },
  { caracteristicasInicio: "Súbita", doenca: "Colecistite" },
  { caracteristicasInicio: "Súbita", doenca: "Intoxicação por chumbo" },
  { caracteristicasInicio: "Súbita", doenca: "Síndrome de Mallory-Weiss" },
  { caracteristicasInicio: "Súbita", doenca: "Divertículo de Meckel" },
  { caracteristicasInicio: "Súbita", doenca: "Ruptura de aneurisma da aorta" },
  { caracteristicasInicio: "Súbita", doenca: "Epiploite ou apendagite" },
  { caracteristicasInicio: "Súbita", doenca: "Ruptura de baço" },
  { caracteristicasInicio: "Súbita", doenca: "Febre familiar do Mediterrâneo" },
  { caracteristicasInicio: "Súbita", doenca: "Prenhez ectópica" },
  { caracteristicasInicio: "Súbita", doenca: "Gastroenterite" },
  { caracteristicasInicio: "Súbita", doenca: "Hematoma do músculo reto" },
  { caracteristicasInicio: "Súbita", doenca: "Hiperlipidemia" },
  { caracteristicasInicio: "Súbita", doenca: "Pancreatite" },
  { caracteristicasInicio: "Súbita", doenca: "Infarto esplênico" },
  { caracteristicasInicio: "Súbita", doenca: "Infarto pulmonar" },
  { caracteristicasInicio: "Súbita", doenca: "Isquemia mesentérica" },
  { caracteristicasInicio: "Súbita", doenca: "Tabes dorsalis" },
  { caracteristicasInicio: "Súbita", doenca: "Yersiniose" },
];
