export const localDaDor = [
  { localDaDor: "difusa", doenca: "Doença celíaca" },
  { localDaDor: "difusa", doenca: "Neoplasias" },
  { localDaDor: "difusa", doenca: "Peritonite primária" },
  { localDaDor: "difusa", doenca: "Porfiria aguda" },
  { localDaDor: "difusa", doenca: "Gastroenterite" },
  { localDaDor: "difusa", doenca: "Insuficiência suprarrenal aguda" },
  { localDaDor: "difusa", doenca: "Febre familiar do Mediterrâneo" },
  { localDaDor: "difusa", doenca: "Intoxicação por chumbo" },
  { localDaDor: "difusa", doenca: "Ruptura de baço" },
  { localDaDor: "difusa", doenca: "Ruptura de aneurisma da aorta" },
  { localDaDor: "difusa", doenca: "Doença de Crohn" },
  { localDaDor: "difusa", doenca: "Diverticulite" },
  { localDaDor: "difusa", doenca: "Crise falcêmica" },
  { localDaDor: "difusa", doenca: "Tabes dorsalis" },
  { localDaDor: "difusa", doenca: "Herpes Zoster" },
  { localDaDor: "difusa", doenca: "Úlcera péptica perfurada" },
  { localDaDor: "difusa", doenca: "Ileite por AINE" },
  { localDaDor: "difusa", doenca: "Verminoses" },
  {
    localDaDor: "difusa",
    doenca: "Adenite mesentérica (hiperplasia linfonodular)",
  },
  { localDaDor: "difusa", doenca: "Vasculite associada a IgA" },
  { localDaDor: "difusa", doenca: "Cetoacidose diabética" },
  { localDaDor: "flanco_direito", doenca: "Pielonefrite" },
  { localDaDor: "flanco_direito", doenca: "Infarto pulmonar" },
  { localDaDor: "flanco_direito", doenca: "Compressão de raízes nervosas" },
  { localDaDor: "flanco_direito", doenca: "Cólica renal" },
  { localDaDor: "flanco_esquerdo", doenca: "Compressão de raízes nervosas" },
  { localDaDor: "flanco_esquerdo", doenca: "Colite Isquêmica" },
  { localDaDor: "flanco_esquerdo", doenca: "Pielonefrite" },
  { localDaDor: "flanco_esquerdo", doenca: "Epiploite ou apendagite" },
  { localDaDor: "flanco_esquerdo", doenca: "Cólica renal" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Hérnia estrangulada" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Mucocele do apêndice" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Hérnia encarcerada" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Infecção respiratória" },
  {
    localDaDor: "fossa_iliaca_direita",
    doenca: "Adenite mesentérica (hiperplasia linfonodular)",
  },
  { localDaDor: "fossa_iliaca_direita", doenca: "Prenhez ectópica" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Apendicite" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Retocolite ulcerativa" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Febre tifoide" },
  {
    localDaDor: "fossa_iliaca_direita",
    doenca: "Ileite de pacientes imunocomprometidos",
  },
  {
    localDaDor: "fossa_iliaca_direita",
    doenca: "Febre familiar do Mediterrâneo",
  },
  { localDaDor: "fossa_iliaca_direita", doenca: "Torção de cisto de ovário" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Ileite actínica" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Tuberculose intestinal" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Ileite por AINE" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Doença de Crohn" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Salpingite" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Divertículo de Meckel" },
  { localDaDor: "fossa_iliaca_direita", doenca: "Yersiniose" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Retocolite ulcerativa" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Hérnia encarcerada" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Prenhez ectópica" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Epiploite ou apendagite" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Diverticulite" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Salpingite" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Constipação" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Torção de cisto de ovário" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Vólvulo" },
  { localDaDor: "fossa_iliaca_esquerda", doenca: "Hérnia estrangulada" },
  { localDaDor: "hipocondrio_direito", doenca: "Infecção respiratória" },
  { localDaDor: "hipocondrio_direito", doenca: "Infarto pulmonar" },
  { localDaDor: "hipocondrio_direito", doenca: "Abscesso hepático" },
  { localDaDor: "hipocondrio_direito", doenca: "Colecistite" },
  { localDaDor: "hipocondrio_direito", doenca: "Crise falcêmica" },
  { localDaDor: "hipocondrio_direito", doenca: "Hepatite aguda" },
  { localDaDor: "hipocondrio_direito", doenca: "Hiperlipidemia" },
  { localDaDor: "hipocondrio_direito", doenca: "Hérnia diafragmática" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Infarto pulmonar" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Abscesso esplênico" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Úlcera gástrica" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Colite isquêmica" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Ruptura de baço" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Infarto esplênico" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Hérnia diafragmática" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Pericardite" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Pancreatite" },
  { localDaDor: "hipocondrio_esquerdo", doenca: "Infarto agudo do miocárdio" },
  { localDaDor: "regiao_epigastrica", doenca: "Obstrução intestinal" },
  {
    localDaDor: "regiao_epigastrica",
    doenca: "Síndrome da artéria mesentérica superior ",
  },
  {
    localDaDor: "regiao_epigastrica",
    doenca: "Síndrome de hiperemese canabinoide",
  },
  { localDaDor: "regiao_epigastrica", doenca: "Síndrome de Mallory-Weiss" },
  { localDaDor: "regiao_epigastrica", doenca: "Colecistite" },
  { localDaDor: "regiao_epigastrica", doenca: "Gastrite" },
  { localDaDor: "regiao_epigastrica", doenca: "Infarto agudo do miocárdio" },
  {
    localDaDor: "regiao_epigastrica",
    doenca: "Doença do refluxo gastro-esofágico",
  },
  { localDaDor: "regiao_epigastrica", doenca: "Úlcera duodenal" },
  { localDaDor: "regiao_epigastrica", doenca: "Úlcera péptica perfurada" },
  { localDaDor: "regiao_epigastrica", doenca: "Apendicite" },
  {
    localDaDor: "regiao_epigastrica",
    doenca: "Insuficiência suprarrenal aguda",
  },
  { localDaDor: "regiao_epigastrica", doenca: "Isquemia mesentérica" },
  { localDaDor: "regiao_epigastrica", doenca: "Pericardite" },
  { localDaDor: "regiao_epigastrica", doenca: "Infarto pulmonar" },
  { localDaDor: "regiao_epigastrica", doenca: "Pancreatite" },
  { localDaDor: "regiao_epigastrica", doenca: "Abscesso hepático" },
  { localDaDor: "regiao_epigastrica", doenca: "Úlcera gástrica" },
  { localDaDor: "regiao_epigastrica", doenca: "Hiperlipidemia" },
  {
    localDaDor: "regiao_hipogastrica",
    doenca: "Ileite de pacientes imunocomprometidos",
  },
  { localDaDor: "regiao_hipogastrica", doenca: "Tabes dorsalis" },
  { localDaDor: "regiao_hipogastrica", doenca: "Retocolite ulcerativa" },
  { localDaDor: "regiao_hipogastrica", doenca: "Doença inflamatória pélvica" },
  { localDaDor: "regiao_hipogastrica", doenca: "Intolerância a lactose" },
  { localDaDor: "regiao_hipogastrica", doenca: "Endometriose" },
  { localDaDor: "regiao_hipogastrica", doenca: "Ileite actínica" },
  { localDaDor: "regiao_hipogastrica", doenca: "Prenhez ectópica" },
  { localDaDor: "regiao_hipogastrica", doenca: "Infecção urinária" },
  { localDaDor: "regiao_hipogastrica", doenca: "Hematoma do músculo reto" },
  {
    localDaDor: "regiao_mesogastrica",
    doenca: "Ruptura de aneurisma da aorta",
  },
  { localDaDor: "regiao_mesogastrica", doenca: "Obstrução intestinal" },
  { localDaDor: "regiao_mesogastrica", doenca: "Isquemia mesentérica" },
  { localDaDor: "regiao_mesogastrica", doenca: "Verminoses" },
  { localDaDor: "regiao_mesogastrica", doenca: "Vasculite associada a IgA" },
  { localDaDor: "regiao_mesogastrica", doenca: "Cetoacidose diabética" },
  { localDaDor: "regiao_mesogastrica", doenca: "Hematoma do músculo reto" },
  { localDaDor: "regiao_mesogastrica", doenca: "Gastroenterite" },
  { localDaDor: "regiao_mesogastrica", doenca: "Intolerância a lactose" },
  { localDaDor: "regiao_mesogastrica", doenca: "Febre tifoide" },
  { localDaDor: "regiao_mesogastrica", doenca: "Constipação" },
  { localDaDor: "regiao_mesogastrica", doenca: "Vólvulo" },
  { localDaDor: "regiao_mesogastrica", doenca: "Doença celíaca" },
];
