export const dataTipoDor = [
  { tipo_dor: "aperto", doenca: "Abscesso esplênico" },
  { tipo_dor: "aperto", doenca: "Abscesso hepático" },
  { tipo_dor: "aperto", doenca: "Adenite mesentérica (hiperplasia linfonodular)" },
  { tipo_dor: "aperto", doenca: "Constipação" },
  { tipo_dor: "aperto", doenca: "Doença de Crohn" },
  { tipo_dor: "aperto", doenca: "Doença do refluxo gastro-esofágico" },
  { tipo_dor: "aperto", doenca: "Epiploite ou apendagite" },
  { tipo_dor: "aperto", doenca: "Gastrite" },
  { tipo_dor: "aperto", doenca: "Hérnia diafragmática" },
  { tipo_dor: "aperto", doenca: "Hérnia estrangulada" },
  { tipo_dor: "aperto", doenca: "Infarto agudo do miocárdio" },
  { tipo_dor: "aperto", doenca: "Infecção urinária" },
  { tipo_dor: "aperto", doenca: "Pericardite" },
  { tipo_dor: "aperto", doenca: "Pielonefrite" },
  { tipo_dor: "aperto", doenca: "Úlcera gástrica" },
  { tipo_dor: "colica", doenca: "Adenite mesentérica (hiperplasia linfonodular)" },
  { tipo_dor: "colica", doenca: "Cetoacidose diabética" },
  { tipo_dor: "colica", doenca: "Colecistite" },
  { tipo_dor: "colica", doenca: "Colite Isquêmica" },
  { tipo_dor: "colica", doenca: "Constipação" },
  { tipo_dor: "colica", doenca: "Crise falcêmica" },
  { tipo_dor: "colica", doenca: "Cólica renal" },
  { tipo_dor: "colica", doenca: "Diverticulite" },
  { tipo_dor: "colica", doenca: "Divertículo de Meckel" },
  { tipo_dor: "colica", doenca: "Doença celíaca" },
  { tipo_dor: "colica", doenca: "Doença de Crohn" },
  { tipo_dor: "colica", doenca: "Febre tifoide" },
  { tipo_dor: "colica", doenca: "Gastroenterite" },
  { tipo_dor: "colica", doenca: "Hiperlipidemia" },
  { tipo_dor: "colica", doenca: "Ileite de pacientes imunocomprometidos" },
  { tipo_dor: "colica", doenca: "Ileite por AINE" },
  { tipo_dor: "colica", doenca: "Insuficiência suprarrenal aguda" },
  { tipo_dor: "colica", doenca: "Intolerância a lactose" },
  { tipo_dor: "colica", doenca: "Intoxicação por chumbo" },
  { tipo_dor: "colica", doenca: "Neoplasias" },
  { tipo_dor: "colica", doenca: "Obstrução intestinal" },
  { tipo_dor: "colica", doenca: "Pancreatite" },
  { tipo_dor: "colica", doenca: "Prenhez ectópica" },
  { tipo_dor: "colica", doenca: "Retocolite ulcerativa" },
  { tipo_dor: "colica", doenca: "Ruptura de baço" },
  { tipo_dor: "colica", doenca: "Salpingite" },
  { tipo_dor: "colica", doenca: "Síndrome da artéria mesentérica superior " },
  { tipo_dor: "colica", doenca: "Síndrome de hiperemese canabinoide" },
  { tipo_dor: "colica", doenca: "Tabes dorsalis" },
  { tipo_dor: "colica", doenca: "Torção de cisto de ovário" },
  { tipo_dor: "colica", doenca: "Tuberculose intestinal" },
  { tipo_dor: "colica", doenca: "Vasculite associada a IgA" },
  { tipo_dor: "colica", doenca: "Verminoses" },
  { tipo_dor: "colica", doenca: "Vólvulo" },
  { tipo_dor: "colica", doenca: "Yersiniose" },
  { tipo_dor: "constante", doenca: "Abscesso esplênico" },
  { tipo_dor: "constante", doenca: "Abscesso hepático" },
  { tipo_dor: "constante", doenca: "Apendicite" },
  { tipo_dor: "constante", doenca: "Colecistite" },
  { tipo_dor: "constante", doenca: "Crise falcêmica" },
  { tipo_dor: "constante", doenca: "Diverticulite" },
  { tipo_dor: "constante", doenca: "Divertículo de Meckel" },
  { tipo_dor: "constante", doenca: "Doença inflamatória pélvica" },
  { tipo_dor: "constante", doenca: "Endometriose" },
  { tipo_dor: "constante", doenca: "Epiploite ou apendagite" },
  { tipo_dor: "constante", doenca: "Febre familiar do Mediterrâneo" },
  { tipo_dor: "constante", doenca: "Febre tifoide" },
  { tipo_dor: "constante", doenca: "Hepatite aguda" },
  { tipo_dor: "constante", doenca: "Herpes Zoster" },
  { tipo_dor: "constante", doenca: "Hiperlipidemia" },
  { tipo_dor: "constante", doenca: "Hérnia encarcerada" },
  { tipo_dor: "constante", doenca: "Hérnia estrangulada" },
  { tipo_dor: "constante", doenca: "Ileite actínica" },
  { tipo_dor: "constante", doenca: "Ileite de pacientes imunocomprometidos" },
  { tipo_dor: "constante", doenca: "Ileite por AINE" },
  { tipo_dor: "constante", doenca: "Infarto agudo do miocárdio" },
  { tipo_dor: "constante", doenca: "Infarto esplênico" },
  { tipo_dor: "constante", doenca: "Infarto pulmonar" },
  { tipo_dor: "constante", doenca: "Infecção respiratória" },
  { tipo_dor: "constante", doenca: "Infecção urinária" },
  { tipo_dor: "constante", doenca: "Insuficiência suprarrenal aguda" },
  { tipo_dor: "constante", doenca: "Isquemia mesentérica" },
  { tipo_dor: "constante", doenca: "Mucocele do apêndice" },
  { tipo_dor: "constante", doenca: "Neoplasias" },
  { tipo_dor: "constante", doenca: "Pancreatite" },
  { tipo_dor: "constante", doenca: "Pericardite" },
  { tipo_dor: "constante", doenca: "Peritonite primária" },
  { tipo_dor: "constante", doenca: "Pielonefrite" },
  { tipo_dor: "constante", doenca: "Porfiria aguda" },
  { tipo_dor: "constante", doenca: "Ruptura de aneurisma da aorta" },
  { tipo_dor: "constante", doenca: "Salpingite" },
  { tipo_dor: "constante", doenca: "Síndrome da artéria mesentérica superior " },
  { tipo_dor: "constante", doenca: "Síndrome de Mallory-Weiss" },
  { tipo_dor: "constante", doenca: "Torção de cisto de ovário" },
  { tipo_dor: "constante", doenca: "Vasculite associada a IgA" },
  { tipo_dor: "constante", doenca: "Úlcera péptica perfurada" },
  { tipo_dor: "fisgada", doenca: "Apendicite" },
  { tipo_dor: "fisgada", doenca: "Compressão de raízes nervosas" },
  { tipo_dor: "fisgada", doenca: "Doença do refluxo gastro-esofágico" },
  { tipo_dor: "fisgada", doenca: "Doença inflamatória pélvica" },
  { tipo_dor: "fisgada", doenca: "Gastrite" },
  { tipo_dor: "fisgada", doenca: "Hematoma do músculo reto" },
  { tipo_dor: "fisgada", doenca: "Herpes Zoster" },
  { tipo_dor: "fisgada", doenca: "Hérnia encarcerada" },
  { tipo_dor: "fisgada", doenca: "Infarto esplênico" },
  { tipo_dor: "fisgada", doenca: "Intolerância a lactose" },
  { tipo_dor: "fisgada", doenca: "Prenhez ectópica" },
  { tipo_dor: "fisgada", doenca: "Úlcera duodenal" },
  { tipo_dor: "fisgada", doenca: "Úlcera gástrica" },
  { tipo_dor: "superficial", doenca: "Compressão de raízes nervosas" },
  { tipo_dor: "superficial", doenca: "Hematoma do músculo reto" },
];
